# Generated by Django 4.2 on 2023-05-06 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_socialpost_shared_body_socialpost_shared_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialpost',
            name='shared_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
